name: TNT_Rain
version: '1.0-SNAPSHOT'
main: xyz.tntrain.Main
api-version: 1.20
commands:
  tntrain:
    description: Starts and stops the tnt rain
    permission: tntrain.use
    usage: /tntrain <start|stop>
